import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ClientTopHeader } from "@/components/dashboard/client/ClientTopHeader";
import { ClientSidebar } from "@/components/dashboard/client/ClientSidebar";
import ReactQueryProvider from "@/components/ReactQueryProvider";
import { Toaster } from "@/components/ui/toaster";

const geistSans = localFont({
  src: "../../fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "../../fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "SupaEvent | Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ReactQueryProvider>
          <Toaster />
          <div className="flex flex-col h-screen">
            <ClientTopHeader />
            <div className="flex flex-1 overflow-hidden">
              <ClientSidebar />
              <main className="flex-1 overflow-y-auto p-6">
                {children}
              </main>
            </div>

          </div>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
